In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
b = np.array([1, 2, 3])
print(b.shape)

(3,)


In [ ]:
print(a[0, 0])

1


In [ ]:
c = np.arange(1, 10, 2)
print(c)

[1 3 5 7 9]


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(a[0] [0])
print(a[0, 0])
print(a[0])

print(type(a[0]))
print(type(a[0][0]))

1
1
[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
print(a[0])

[4 5 6]


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c = np.linspace(1, 10, 10)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
a = np.arange(1, 4)
b = np.arange(0, 3)
print(a)
print(b)
2*a

[1 2 3]
[0 1 2]


array([2, 4, 6])

In [ ]:
a = [1, 2, 3]
b = [3, 4]
print(a+b)

print('hello'*2)

[1, 2, 3, 3, 4]
hellohello


In [ ]:
a = np.array([1, 2, 3])
print(a >= 2)

print(a[a >= 2])

[False  True  True]
[2 3]


In [ ]:
b = np.array([10, 20, 30])

print(b > 10)
print(b[b > 10])

[False  True  True]
[20 30]


In [ ]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print()
print(a % 2 == 0)
print()
print(a[a % 2 == 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[False  True False]
 [ True False  True]
 [False  True False]]

[2 4 6 8]


In [ ]:
a[:, 2] > 5

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a)
s = np.sum(a, axis = 0)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [ ]:
d = np.arange(1, 6)
print(d)
print(d[[1, 3]])

[1 2 3 4 5]
[2 4]


In [ ]:
menu = {'모카라떼' : 3500}
a = str(input())
print(a in menu)

모카라떼
True
