## #1
- 다음 2차원 배열을 생성하시오.

$\begin{bmatrix}1&2&3\\4&5&6\\7&8&9\\ \end{bmatrix}$




In [2]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## #2
- 앞서 출력된 결과에서 Slicing 또는 Indexing을 사용하여 다음 형태의 배열을 출력하시오. 


(1) $\begin{bmatrix} 7&8&9 \end{bmatrix}$

(2) $\begin{bmatrix} 1\\4\\7 \end{bmatrix}$

(3) $\begin{bmatrix}4&5\\7&8 \end{bmatrix}$

(4) $\begin{bmatrix}3&2\\6&5 \end{bmatrix}$

## #3
 - Boolean Indexing을 이용하여 #1에서 생성한 배열 원소들 중 홀수로만 구성된 배열을 출력하시오.

## #4
- #1에서 생성한 배열을 이용하여 다음 배열을 출력하시오.

$\begin{bmatrix}1&4&7\\2&5&8\\3&6&9\\ \end{bmatrix}$

In [3]:
b = a.T
b

'''
Transpose 
'''

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## #5

(1) 다음 1차원 배열을 생성하시오.

$\begin{bmatrix}1&4&7&10 \end{bmatrix}$

(2) 생성한 1차원 배열에서 Fancy Indexing을 이용하여 다음을 출력하시오.

$\begin{bmatrix}10&1 \end{bmatrix}$

In [4]:
c = np.array([1, 4, 7, 10])
c

array([ 1,  4,  7, 10])

In [6]:
c[[3, 0]]

array([10,  1])